name: first workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: A welcome message
        run: echo "Welcome to my first project!"
